name: Create Archive
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'sw-resourcepack.zip'
        exclusions: '*.git*'
    - uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: "latest"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sw-resourcepack.zip"
        tag: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
      
