name: Create Archive
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'sw-rp.zip'
        exclusions: '*.git*'
    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yy.mm.i'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sw-resourcepack.zip"
        tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        draft: false
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
      
