name: Create Archive
on: 
  push:
    tags:
    - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'sw-resourcepack.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sw-resourcepack.zip"
        draft: false
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
      
