name: Create Archive
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: DamianReeves/write-file-action@master
      with:
        path: .version
        contents: |
            ${{ github.event.repository.updated_at }}
        write-mode: overwrite
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'sw-rp.zip'
        exclusions: '*.git* LICENSE'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sw-rp.zip, .version"
        tag: latest
        allowUpdates: true
        draft: false
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
      
