name: Create Archive
on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'sw-rp.zip'
        exclusions: '*.git*'
    - uses: dev-drprasad/delete-tag-and-release@v1.0 # PRERELEASE is v1.0 and can also be used to test and give us feedback
      with:
        tag_name: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "sw-rp.zip"
        tag: latest
        draft: false
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
      
